import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <a href='https://jaavin.ca'>
              Click here for simple portfolio
            </a>
          </p>
          <div>
          </div>
        </div>

        <div className={styles.content}>
          <div className={styles.header}>
            Hello👋, I'm Jaavin. 
          </div>
          <div className={styles.headerinfo}>
            I love solving problems and learning! I am an Engineering 1 student at McMaster University interested in robotics and rockets! 🚧 Under Construction 🚧 
          </div>
          <div className={styles.images}>
            <div className={styles.gallery}>
              <img src='jaavin.png'></img>
              <div className={styles.subtitle}>Me :)</div>
            </div>
            <div className={styles.gallery2}>
              <img src='1325.jpg'></img>
              <div className={styles.subtitle2}>1325 at
                2022 FIRST Ontario Provincial Championship</div>
            </div>
            <div className={styles.gallery3}>
              <img src='macrocket.png'></img>
              <div className={styles.subtitle2}>Marauder 1 at Launch Canada</div>
            </div>
          </div>

        </div>


        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Projects
            </h2>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              About
            </h2>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Contact
            </h2>
          </a>

        </div>
      </main>
    </>
  )
}
